### ISSUE TITLE
Update Doc Strings

### ISSUE THREAD

**Issue by noraa-july-stoke** [noraa-july-stoke/tangerine#6]
Some of the classes don't have docstrings finished. All classes and their methods should have robust multiline docstrings.

**Comment by Kkorbin** [comment]
Hello, Id like to give this a try. I am brand new at contributing, but I think documentation is something I can handle. Let me know if there is anything I should know!

**Comment by Kkorbin** [comment]
Thanks for the approval. I will look into adding doc strings to the rest of the code now 👍 Do you want to assign this to me?

**Comment by noraa-july-stoke** [comment]
@Kkorbin go right ahead!

**Comment by noraa-july-stoke** [comment]
@Kkorbin go right ahead!

**Comment by DeVcB13d** [comment]
Hey, I am new to contributing and recently came across this, can I try writing the docs?

**Comment by noraa-july-stoke** [comment]
@DeVcB13d Sure! Go ahead and  feel free to look around and see if you can find anything that needs fixing. I'm sure there's some things in there that could get polished up a bit!
